Driver Interface Enhancements
awslabs/amazon-qldb-driver-go pull request #44
Opened 2021-03-22 18:15 UTC by justing-bq

Adjustments to the logger and result interfaces.

Meant to address https://github.com/awslabs/amazon-qldb-driver-go/issues/38

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-03-23 21:48 UTC, simonz-bq approved these changes
LGTM

2021-03-25 17:56 UTC, alpian reviewed
Can we get a more descriptive comment on these changes please? "Driver Enhancements" is a little vague :)

2021-03-29 07:39 UTC, alpian requested changes
Let's add the test for the upsert that @mousedownmike is trying to implement as an example test and also to prove we achieved the desired result.

2021-03-31 17:56 UTC, alpian approved these changes

2021-03-31 18:00 UTC, merged